-file("/usr/local/lib/erlang/lib/parsetools-2.1.4/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(beat_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/beat_lexer.xrl", 134).

-export([is_reserved/1]).

make_token(Name, Line, Chars) when is_list(Chars) ->
    {token, {Name, Line, list_to_atom(Chars)}};
make_token(Name, Line, Chars) ->
    {token, {Name, Line, Chars}}.

make_token(Name, Line, Chars, Fun) ->
    {token, {Name, Line, Fun(Chars)}}.

endls(Chars) ->
    lists:filter(fun (C) -> C == $\n orelse C == $; end, Chars).

atom_or_identifier(String, TokenLine) ->
     case is_reserved(String) of
         true ->
            {list_to_atom(String), TokenLine};
         false ->
            {atom, TokenLine, build_atom(String, TokenLine)}
     end.

is_reserved("after")   -> true;
is_reserved("begin")   -> true;
is_reserved("case")    -> true;
is_reserved("catch")   -> true;
is_reserved("do")      -> true;
is_reserved("else")    -> true;
is_reserved("end")     -> true;
is_reserved("fn")      -> true;
is_reserved("for")     -> true;
is_reserved("if")      -> true;
is_reserved("in")      -> true;
is_reserved("match")   -> true;
is_reserved("receive") -> true;
is_reserved("try")     -> true;
is_reserved("when")    -> true;

is_reserved("def")     -> true;

is_reserved("cond")    -> true;
is_reserved("let")     -> true;
is_reserved("of")      -> true;

is_reserved(_)         -> false.

build_atom_string(Chars, Line, Len) ->
  String = unescape_string(lists:sublist(Chars, 2, Len - 2), Line),
  {token, {atom, Line, list_to_atom(String)}}.

build_string(Type, Chars, Line, Len) ->
  String = unescape_string(lists:sublist(Chars, 2, Len - 2), Line),
    {token, {Type, Line, String}}.

unescape_string(String, Line) -> unescape_string(String, Line, []).

unescape_string([], _Line, Output) ->
  lists:reverse(Output);
unescape_string([$\\, Escaped | Rest], Line, Output) ->
  Char = map_escaped_char(Escaped, Line),
  unescape_string(Rest, Line, [Char|Output]);
unescape_string([Char|Rest], Line, Output) ->
  unescape_string(Rest, Line, [Char|Output]).

map_escaped_char(Escaped, Line) ->
  case Escaped of
    $\\ -> $\\;
    $/ -> $/;
    $\" -> $\";
    $\' -> $\';
    $\( -> $(;
    $b -> $\b;
    $d -> $\d;
    $e -> $\e;
    $f -> $\f;
    $n -> $\n;
    $r -> $\r;
    $s -> $\s;
    $t -> $\t;
    $v -> $\v;
    _ -> throw({error, {Line, beat_lexer, ["unrecognized escape sequence: ", [$\\, Escaped]]}})
  end.

build_atom(Atom, _Line) -> list_to_atom(Atom).

-file("/usr/local/lib/erlang/lib/parsetools-2.1.4/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/beat_lexer.erl", 387).
yystate() -> 79.

yystate(86, [116|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,86};
yystate(85, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(84, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(83, [32|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 45, Tlen);
yystate(83, [13|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 45, Tlen);
yystate(83, [10|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line+1, Tlen+1, 45, Tlen);
yystate(83, [9|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 45, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line,83};
yystate(82, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(81, [61|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 15, Tlen);
yystate(81, [60|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 15, Tlen);
yystate(81, [45|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 15, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,81};
yystate(80, [110|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,80};
yystate(79, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(79, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 98, C =< 101 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 109 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 119 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,78};
yystate(77, [62|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, [61|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,77};
yystate(76, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(75, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line};
yystate(74, [43|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 11, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,74};
yystate(73, [45|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 0, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,73};
yystate(72, [115|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(70, [97|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 41, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(68, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line+1, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(65, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line};
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(62, [108|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,62};
yystate(61, [62|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 15, Tlen);
yystate(61, [61|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 15, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,61};
yystate(60, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line+1, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(59, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(57, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(56, [116|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(54, [115|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(52, [92|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, [39|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, [10|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line+1, Tlen+1, 39, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(36, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(36, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(36, Ics, Line, Tlen+1, 39, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,52};
yystate(51, [32|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 44, Tlen);
yystate(51, [13|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 44, Tlen);
yystate(51, [10|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line+1, Tlen+1, 44, Tlen);
yystate(51, [9|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 44, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line,51};
yystate(50, [62|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 33, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,50};
yystate(49, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(48, [111|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,48};
yystate(47, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(46, [62|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 11, Tlen);
yystate(46, [45|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 11, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line};
yystate(43, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(42, [110|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,42};
yystate(41, [61|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 31, Tlen);
yystate(41, [58|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 31, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,41};
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,40};
yystate(39, [111|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(37, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(36, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line+1, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,35};
yystate(34, [100|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(32, [114|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(15, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,32};
yystate(31, [114|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,31};
yystate(30, [47|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 12, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(28, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(27, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [100|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,26};
yystate(25, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(24, [114|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,24};
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,23};
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line+1, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(19, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line};
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 8, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,18};
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 18, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Tlen+1, 18, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,16};
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,15};
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,14};
yystate(13, [96|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, [92|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, [10|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line+1, Tlen+1, 42, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(10, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 91 ->
    yystate(10, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(10, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(10, Ics, Line, Tlen+1, 42, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(11, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [34|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [10|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line+1, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(27, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(27, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(27, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,11};
yystate(10, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line+1, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [101|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,8};
yystate(7, [114|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,7};
yystate(6, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line+1, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line+1, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line+1, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line};
yystate(1, [101|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [69|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,1};
yystate(0, [117|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(15, Ics, Line, Tlen+1, 41, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLen, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLen, TokenLine);
yyaction(40, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_40(TokenChars, TokenLine);
yyaction(41, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_41(TokenChars, TokenLine);
yyaction(42, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_42(TokenChars, TokenLen, TokenLine);
yyaction(43, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_43(TokenChars, TokenLine);
yyaction(44, _, _, _) ->
    yyaction_44();
yyaction(45, _, _, _) ->
    yyaction_45();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 66).
yyaction_0(TokenChars, TokenLine) ->
     make_token (bin_shift, TokenLine, TokenChars) .

-compile({inline,yyaction_1/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 67).
yyaction_1(TokenChars, TokenLine) ->
     make_token (bin_not, TokenLine, TokenChars) .

-compile({inline,yyaction_2/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 68).
yyaction_2(TokenChars, TokenLine) ->
     make_token (bin_and, TokenLine, TokenChars) .

-compile({inline,yyaction_3/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 69).
yyaction_3(TokenChars, TokenLine) ->
     make_token (bin_or, TokenLine, TokenChars) .

-compile({inline,yyaction_4/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 72).
yyaction_4(TokenChars, TokenLine) ->
     make_token (bool_not, TokenLine, TokenChars) .

-compile({inline,yyaction_5/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 73).
yyaction_5(TokenChars, TokenLine) ->
     make_token (boolean, TokenLine, TokenChars) .

-compile({inline,yyaction_6/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 74).
yyaction_6(TokenChars, TokenLine) ->
     make_token (bool_and, TokenLine, TokenChars) .

-compile({inline,yyaction_7/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 75).
yyaction_7(TokenChars, TokenLine) ->
     make_token (bool_or, TokenLine, TokenChars) .

-compile({inline,yyaction_8/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 76).
yyaction_8(TokenChars, TokenLine) ->
     make_token (bool_andd, TokenLine, TokenChars) .

-compile({inline,yyaction_9/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 77).
yyaction_9(TokenChars, TokenLine) ->
     make_token (bool_orr, TokenLine, TokenChars) .

-compile({inline,yyaction_10/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 78).
yyaction_10(TokenChars, TokenLine) ->
     make_token (bool_xor, TokenLine, TokenChars) .

-compile({inline,yyaction_11/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 81).
yyaction_11(TokenChars, TokenLine) ->
     make_token (add_op, TokenLine, TokenChars) .

-compile({inline,yyaction_12/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 82).
yyaction_12(TokenChars, TokenLine) ->
     make_token (mul_op, TokenLine, TokenChars) .

-compile({inline,yyaction_13/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 83).
yyaction_13(TokenChars, TokenLine) ->
     make_token (assign, TokenLine, TokenChars) .

-compile({inline,yyaction_14/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 85).
yyaction_14(TokenChars, TokenLine) ->
     make_token (coloneq, TokenLine, TokenChars) .

-compile({inline,yyaction_15/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 87).
yyaction_15(TokenChars, TokenLine) ->
     make_token (comp_op, TokenLine, TokenChars) .

-compile({inline,yyaction_16/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 90).
yyaction_16(TokenChars, TokenLine) ->
     make_token (concat_op, TokenLine, TokenChars) .

-compile({inline,yyaction_17/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 93).
yyaction_17(TokenChars, TokenLine) ->
     make_token (float, TokenLine, TokenChars, fun erlang : list_to_float / 1) .

-compile({inline,yyaction_18/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 94).
yyaction_18(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun erlang : list_to_integer / 1) .

-compile({inline,yyaction_19/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 97).
yyaction_19(TokenChars, TokenLine) ->
     make_token (open, TokenLine, TokenChars) .

-compile({inline,yyaction_20/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 98).
yyaction_20(TokenChars, TokenLine) ->
     make_token (close, TokenLine, TokenChars) .

-compile({inline,yyaction_21/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 99).
yyaction_21(TokenChars, TokenLine) ->
     make_token (open_list, TokenLine, TokenChars) .

-compile({inline,yyaction_22/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 100).
yyaction_22(TokenChars, TokenLine) ->
     make_token (close_list, TokenLine, TokenChars) .

-compile({inline,yyaction_23/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 101).
yyaction_23(TokenChars, TokenLine) ->
     make_token (open_map, TokenLine, TokenChars) .

-compile({inline,yyaction_24/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 102).
yyaction_24(TokenChars, TokenLine) ->
     make_token (close_map, TokenLine, TokenChars) .

-compile({inline,yyaction_25/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 104).
yyaction_25(TokenChars, TokenLine) ->
     make_token (sep, TokenLine, TokenChars) .

-compile({inline,yyaction_26/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 105).
yyaction_26(TokenChars, TokenLine) ->
     make_token (semicolon, TokenLine, TokenChars) .

-compile({inline,yyaction_27/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 106).
yyaction_27(TokenChars, TokenLine) ->
     make_token (send_op, TokenLine, TokenChars) .

-compile({inline,yyaction_28/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 107).
yyaction_28(TokenChars, TokenLine) ->
     make_token (hash, TokenLine, TokenChars) .

-compile({inline,yyaction_29/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 108).
yyaction_29(TokenChars, TokenLine) ->
     make_token (at, TokenLine, TokenChars) .

-compile({inline,yyaction_30/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 109).
yyaction_30(TokenChars, TokenLine) ->
     make_token (cons_op, TokenLine, TokenChars) .

-compile({inline,yyaction_31/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 110).
yyaction_31(TokenChars, TokenLine) ->
     make_token (colon, TokenLine, TokenChars) .

-compile({inline,yyaction_32/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 111).
yyaction_32(TokenChars, TokenLine) ->
     make_token (dot, TokenLine, TokenChars) .

-compile({inline,yyaction_33/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 112).
yyaction_33(TokenChars, TokenLine) ->
     make_token (arrow, TokenLine, TokenChars) .

-compile({inline,yyaction_34/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 113).
yyaction_34(TokenChars, TokenLine) ->
     make_token (arrowend, TokenLine, TokenChars) .

-compile({inline,yyaction_35/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 114).
yyaction_35(TokenChars, TokenLine) ->
     make_token (larrow, TokenLine, TokenChars) .

-compile({inline,yyaction_36/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 115).
yyaction_36(TokenChars, TokenLine) ->
     make_token (larrowend, TokenLine, TokenChars) .

-compile({inline,yyaction_37/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 116).
yyaction_37(TokenChars, TokenLine) ->
     make_token (fatarrow, TokenLine, TokenChars) .

-compile({inline,yyaction_38/3}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 119).
yyaction_38(TokenChars, TokenLen, TokenLine) ->
     build_string (string, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_39/3}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 120).
yyaction_39(TokenChars, TokenLen, TokenLine) ->
     build_string (bstring, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_40/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 123).
yyaction_40(TokenChars, TokenLine) ->
     make_token (var, TokenLine, TokenChars) .

-compile({inline,yyaction_41/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 124).
yyaction_41(TokenChars, TokenLine) ->
     { token, atom_or_identifier (TokenChars, TokenLine) } .

-compile({inline,yyaction_42/3}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 125).
yyaction_42(TokenChars, TokenLen, TokenLine) ->
     build_atom_string (TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_43/2}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 128).
yyaction_43(TokenChars, TokenLine) ->
     make_token (nl, TokenLine, endls (TokenChars)) .

-compile({inline,yyaction_44/0}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 129).
yyaction_44() ->
     skip_token .

-compile({inline,yyaction_45/0}).
-file("/Users/otto/numericit/beat/_build/default/lib/beat/src/fn_lexer.xrl", 130).
yyaction_45() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.1.4/include/leexinc.hrl", 309).
